package little.goose.design.system.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFB02B36)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD8)
val md_theme_light_onPrimaryContainer = Color(0xFF410008)
val md_theme_light_secondary = Color(0xFF8C5000)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDCBF)
val md_theme_light_onSecondaryContainer = Color(0xFF2D1600)
val md_theme_light_tertiary = Color(0xFF8432C7)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF1DAFF)
val md_theme_light_onTertiaryContainer = Color(0xFF2D004F)
val md_theme_light_error = Color(0xFF006D34)
val md_theme_light_errorContainer = Color(0xFF69FE97)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF00210B)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A1A)
val md_theme_light_outline = Color(0xFF85736C)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEC)
val md_theme_light_inverseSurface = Color(0xFF362F2E)
val md_theme_light_inversePrimary = Color(0xFFFFB3B1)
val md_theme_light_surfaceTint = Color(0xFFB02B36)
val md_theme_light_outlineVariant = Color(0xFFD7C2B9)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFF8F7)
val md_theme_light_onSurface = Color(0xFF201A1A)
val md_theme_light_surfaceVariant = Color(0xFFF4DED5)
val md_theme_light_onSurfaceVariant = Color(0xFF52443D)

val md_theme_dark_primary = Color(0xFFFFB3B1)
val md_theme_dark_onPrimary = Color(0xFF680012)
val md_theme_dark_primaryContainer = Color(0xFF8F0F21)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD8)
val md_theme_dark_secondary = Color(0xFFFFB872)
val md_theme_dark_onSecondary = Color(0xFF4A2800)
val md_theme_dark_secondaryContainer = Color(0xFF6A3B00)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCBF)
val md_theme_dark_tertiary = Color(0xFFDFB7FF)
val md_theme_dark_onTertiary = Color(0xFF4B007E)
val md_theme_dark_tertiaryContainer = Color(0xFF6A06AE)
val md_theme_dark_onTertiaryContainer = Color(0xFFF1DAFF)
val md_theme_dark_error = Color(0xFF48E17E)
val md_theme_dark_errorContainer = Color(0xFF005225)
val md_theme_dark_onError = Color(0xFF003918)
val md_theme_dark_onErrorContainer = Color(0xFF69FE97)
val md_theme_dark_background = Color(0xFF201A1A)
val md_theme_dark_onBackground = Color(0xFFEDE0DE)
val md_theme_dark_outline = Color(0xFFA08D85)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1A)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DE)
val md_theme_dark_inversePrimary = Color(0xFFB02B36)
val md_theme_dark_surfaceTint = Color(0xFFFFB3B1)
val md_theme_dark_outlineVariant = Color(0xFF52443D)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF181211)
val md_theme_dark_onSurface = Color(0xFFD0C4C2)
val md_theme_dark_surfaceVariant = Color(0xFF52443D)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C2B9)


val seed = Color(0xFFFF656A)
