package little.goose.design.system.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFB02C31)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD7)
val md_theme_light_onPrimaryContainer = Color(0xFF410005)
val md_theme_light_secondary = Color(0xFF984716)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBCB)
val md_theme_light_onSecondaryContainer = Color(0xFF341100)
val md_theme_light_tertiary = Color(0xFF2E5DA8)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD7E2FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001A40)
val md_theme_light_error = Color(0xFF006D34)
val md_theme_light_errorContainer = Color(0xFF69FE97)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF00210B)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A19)
val md_theme_light_outline = Color(0xFF84746A)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEC)
val md_theme_light_inverseSurface = Color(0xFF362F2E)
val md_theme_light_inversePrimary = Color(0xFFFFB3AF)
val md_theme_light_surfaceTint = Color(0xFFB02C31)
val md_theme_light_outlineVariant = Color(0xFFD7C3B8)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFF8F7)
val md_theme_light_onSurface = Color(0xFF201A19)
val md_theme_light_surfaceVariant = Color(0xFFF4DED3)
val md_theme_light_onSurfaceVariant = Color(0xFF52443C)

val md_theme_dark_primary = Color(0xFFFFB3AF)
val md_theme_dark_onPrimary = Color(0xFF68000E)
val md_theme_dark_primaryContainer = Color(0xFF8E111C)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD7)
val md_theme_dark_secondary = Color(0xFFFFB692)
val md_theme_dark_onSecondary = Color(0xFF552000)
val md_theme_dark_secondaryContainer = Color(0xFF793100)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBCB)
val md_theme_dark_tertiary = Color(0xFFACC7FF)
val md_theme_dark_onTertiary = Color(0xFF002F67)
val md_theme_dark_tertiaryContainer = Color(0xFF08458E)
val md_theme_dark_onTertiaryContainer = Color(0xFFD7E2FF)
val md_theme_dark_error = Color(0xFF48E17E)
val md_theme_dark_errorContainer = Color(0xFF005225)
val md_theme_dark_onError = Color(0xFF003918)
val md_theme_dark_onErrorContainer = Color(0xFF69FE97)
val md_theme_dark_background = Color(0xFF201A19)
val md_theme_dark_onBackground = Color(0xFFEDE0DE)
val md_theme_dark_outline = Color(0xFF9F8D83)
val md_theme_dark_inverseOnSurface = Color(0xFF201A19)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DE)
val md_theme_dark_inversePrimary = Color(0xFFB02C31)
val md_theme_dark_surfaceTint = Color(0xFFFFB3AF)
val md_theme_dark_outlineVariant = Color(0xFF52443C)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF181211)
val md_theme_dark_onSurface = Color(0xFFD0C4C2)
val md_theme_dark_surfaceVariant = Color(0xFF52443C)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C3B8)


val seed = Color(0xFFFF6665)
